### ISSUE TITLE
No error handling for improper input

### ISSUE THREAD

**Issue by o4ugDF54PlqU** [Pacutacatete100/Shut-The-Box#1]
![image](https://user-images.githubusercontent.com/36900762/83830590-86413a80-a6b3-11ea-95ca-723306d31a39.png)

**Comment by o4ugDF54PlqU** [comment]
Also, why do you lose if you roll 4?

**Comment by Pacutacatete100** [comment]
fixed error handling in the recent commit, you lose when you rolled 4 because of the variant of the game you were playing
